---
# This is the top-level playbook

- hosts: mail
  become: true
  vars_files:
  - group_vars/ssh-connection.yml
  roles:
    - general
    - mail/general
    - mail/certbot
    - mail/mariadb
    - mail/dovecot
    - mail/postfix
    - mail/rspamd
    - mail/postfixadmin
    - mail/rspamd-gui

- hosts: kanban
  become: true
  vars_files:
  - group_vars/ssh-connection.yml
  roles:
    - general
    - wekan
