---
#  become: true
#  gather_facts: no
#  vars:
#  domain_name: kanban.tsec901g3.tk
#  letsencrypt_email: eloi.carlot-pascal@epitech.eu
- name: Update / Upgrade APT
  apt:
    upgrade: dist
    update_cache: yes

- name: Snapd installation
  apt:
    name: snapd
    state: present

- name: Snap install / refresh core
  shell: sudo snap install core; sudo snap refresh core

- name: Wekan Installation
  snap:
    name: wekan
    classic: yes

- name: Set wekan port
  shell: snap set wekan port='3001'; snap set wekan root-url='https://kanban.tsec901g3.tk'

- name: Enable and start wekan
  shell: systemctl enable snap.wekan.wekan; systemctl restart snap.wekan.wekan

- name: Nginx Installation
  apt:
    name: nginx
    state: present

- name: Set nginx bucket size
  shell: sed -i "/server_names_hash_bucket_size/s/# //g" /etc/nginx/nginx.conf

- name: Restart nginx
  service: name=nginx state=restarted

- name: Remove default nginx config
  file: name=/etc/nginx/sites-enabled/default state=absent

- name: Create nginx conf for wekan
  template:
    src: templates/wekan.conf
    dest: /etc/nginx/conf.d/wekan.conf

- name: Restart nginx for activate wekan site
  service: name=nginx state=restarted

- name: Add debian apt repo
  shell: echo "deb http://ftp.debian.org/debian buster-backports main" >> /etc/apt/sources.list; apt update -y

- name: Certbot Installation
  snap:
    name: certbot
    classic: yes

- name: Link certbot binary
  shell: sudo ln -s /snap/bin/certbot /usr/bin/certbot
  ignore_errors: yes

- name: Create certificate for wekan
  shell: sudo certbot --nginx -n -m {{ certbot_email }} --agree-tos -d {{ kaban_domain_name }}

- name: Setup LDAP for wekan
	shell: snap set wekan caddy-enabled='false'; snap set wekan default-authentication-method='ldap'; snap set wekan ldap-authentication='true'; snap set wekan ldap-authentication-password='y7pcASQ7T77S'; snap set wekan ldap-authentication-userdn='cn=admin,dc=tsec901g3,dc=tk'; snap set wekan ldap-background-sync='true'; snap set wekan ldap-background-sync-import-new-users='true'; snap set wekan ldap-background-sync-interval='every 1 minute'; snap set wekan ldap-basedn='dc=tsec901g3,dc=tk', snap set wekan ldap-email-field='mail'; snap set wekan ldap-enable='true'; snap set wekan ldap-fullname-field='cn'; snap set wekan ldap-group-filter-enable='false'; snap set wekan ldap-group-filter-id-attribute='cn'; snap set wekan ldap-host='ldap.tsec901g3.tk'; snap set wekan ldap-log-enabled='false'; snap set wekan ldap-login-fallback='true'; snap set wekan ldap-merge-existing-users='true'; snap set wekan ldap-port='389'; snap set wekan ldap-user-search-field='uid'; snap set wekan ldap-user-search-filter='(&(objectclass=inetOrgPerson))'; snap set wekan ldap-user-search-scope='sub'; snap set wekan ldap-username-field='uid'

