---
# Tasks file for dovecot

- name: Ensure directory templates structure exists
  file:
    path: '/etc/dovecot/{{ item.path }}'
    state: directory
  with_filetree: templates/
  when: item.state == 'directory'

- name: Ensure directory files structure exists
  file:
    path: '/etc/dovecot/{{ item.path }}'
    state: directory
  with_filetree: files/
  when: item.state == 'directory'

- name: Template dovecot
  template:
    src: '{{ item.src }}'
    dest: '/etc/dovecot/{{ item.path }}'
    mode: "0644"
  with_filetree: templates/
  when: item.state == 'file'
  tags: dovecot

- name: Copy dovecot files
  copy:
    src: '{{ item.src }}'
    dest: '/etc/dovecot/{{ item.path }}'
    owner: vmail
    group: vmail
    mode: "0644"
  with_filetree: files/
  when: item.state == 'file'
  tags: dovecot

- name: restart dovecot
  service:
    name: dovecot
    state: restarted
  tags: dovecot
