---
firewall:
  interface: eth0
  rules:
    - "22"
    - "80,443"

## Domain name for the installation
meet_domain: jitsi2.tsec901g3.tk

# Mail for let's encrypt certs
le_email: nathan1.lagrange@epitech.eu
# Use debian's certbot
debian_certbot: true
# Auth (none, ldap, token)
xmpp_auth: none
# Allow guest users (when using auth)
allow_guests: false

# token configuration
token_auth_appid: YOUR_APP_ID
token_auth_appsecret: "{{ vault_token_auth_appsecret }}"

## LDAP configuration for saslauthd
saslauthd_ldap_config: |
  ldap_servers: ldap://127.0.0.1/
  ldap_search_base: ou=PEOPLE,dc=YOURDOMAIN,dc=ES
  ldap_filter: (uid=%u)
  ldap_version: 3
  ldap_auth_method: bind

## This shouldn't be necessary,...
## but sometimes download.jitsi.org is not fast enough for apt_key
use_included_jitsi_gpg_key: false

## Recording
enable_recording: false
add_participants_metadata: false
recording_directory: /home/jibri/recs
# Script to execute after recording is finished
recording_processing_script: /dev/null

## octo support
octo_enabled: false
# strategy: either RegionBasedBridgeSelectionStrategy or SplitBridgeSelectionStrategy
octo_strategy: RegionBasedBridgeSelectionStrategy
# default port for octo networking
octo_bind_port: 4096
# default region for those videobridges not having one set
octo_region: none

## turn support
## TODO: Currently TURN server support is limited to running it only on the "central" server
##       next to nginx, prosody and jicofo, and sharing SSL certificate with them
turn_enabled: false
turn_secret: "{{ vault_turn_secret }}"

# Meet
# Limit the number of videostreams to clients (-1 -> no limit)
channelLastN: -1
defaultLanguage: en

# Jicofo
jicofo_user: focus  # DO NOT change this, ignored by jicofo postinst, hardcoded god knows where else
jicofo_pass: "{{ vault_jicofo_pass }}"
# Jicofo Component secret (debconf: jicofo/jicofosecret
jicofo_secret: "{{ vault_jicofo_secret }}"

## prometheus jvb exporter (installs docker and runs a container for it)
run_exporter_container: false
exporter_xmpp_user: prometheus
exporter_xmpp_pass: "{{ vault_exporter_xmpp_pass }}"

## Videobridge XMPP credetials (if running jvb in this host)
videobridge_user: nathan
videobridge_pass: "{{ vault_videobridge_pass }}"
# Set this to something different that "videobridge_user" if you want to share
# videobridge_user and videobridge_pass across different videobridges
videobridge_muc_nick: nathan
## octo configuration (optional)
# octo_region: some_region
## bind_address is only required if not using the IP address asociated
## with the default route (as in "the default IP address")
# octo_bind_address:
## public_address is only required if the bind IP address is not reachable
## by the rest of the videobridges. Usually when bind_address is in a private
## network and there's some kind of NAT from this IP address to the bind_address
# octo_public_address:

## Jibri XMPP credetials (if running jibri in this host)
jibri_user: jibri_CHANGEME
jibri_pass: "{{ vault_jibri_pass }}"
# Set this to something different that "videobridge_user" if you want to share
# videobridge_user and videobridge_pass across different videobridges
jibri_muc_nick: jibri_CHANGEME

