---
firewall:
  interface: enp0s3
  rules:
    - "22"
    - "25"
    - "587"
    - "993"

host: T-SEC-MAIL
ip_address: "{{ ansible_default_ipv4.address }}"
mail_fqdn: "{{ domain }}"
smtp_fqdn: "smtp.{{ domain }}"
postfixadmin_fqdn: "postfix.{{ domain }}"
imap_fqdn: imap.{{ domain }}
mail_user: admin
email_for_updates: "{{ mail_user }}@{{ domain }}"

ldap: "ldap"
mysql: "mysql"

data_source: "{{ ldap }}"

# relay host
relay:
  use: true
  smtp: "[smtp.gmail.com]:587"
  mail: "thomas.otxoa@gmail.com"
